### ISSUE TITLE
[BUG] Incompatibility with numba versions later than 0.48.0

### ISSUE THREAD

**Issue by paul-tqh-nguyen** [rapidsai/cugraph#850]
**Describe the bug**
cugraph doesn't work with versions of numba beyond 0.48.0

This causes problems when installing cugraph using instructions in the cugraph README.

```
/home/pnguyen/miniconda3/envs/temporary_environment/lib/python3.7/site-packages/cudf/core/column/categorical.py:12: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import requested from: 'numba.numpy_support', please update to use 'numba.np.numpy_support' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from cudf._libxx.transform import bools_to_mask
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pnguyen/miniconda3/envs/temporary_environment/lib/python3.7/site-packages/cudf/__init__.py", line 7, in <module>
    from cudf import core, datasets
  File "/home/pnguyen/miniconda3/envs/temporary_environment/lib/python3.7/site-packages/cudf/core/__init__.py", line 5, in <module>
    from cudf.core.dataframe import DataFrame, from_pandas, merge
  File "/home/pnguyen/miniconda3/envs/temporary_environment/lib/python3.7/site-packages/cudf/core/dataframe.py", line 43, in <module>
    from cudf.utils import applyutils, ioutils, queryutils, utils
  File "/home/pnguyen/miniconda3/envs/temporary_environment/lib/python3.7/site-packages/cudf/utils/applyutils.py", line 6, in <module>
    from numba import cuda, six
ImportError: cannot import name 'six' from 'numba' (/home/pnguyen/miniconda3/envs/temporary_environment/lib/python3.7/site-packages/numba/__init__.py)
```
It seems that six is being imported from numba. 

**To Reproduce**

Here's what I run to get the problem:
<details>

(base) pnguyen@demouser-DGX-Station:/tmp$ yes | conda create -n temporary_environment python=3.7 && \
conda activate temporary_environment && \
yes | conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults cugraph cudatoolkit=10.1  && \
printf "\n\n\n\n" && \
python3 -c "import cudf, cugraph; print(f'cudf {cudf.__version__} \ncugraph {cugraph.__version__}')" && \
printf "\n\n\n\n" && \
conda deactivate && \
conda env remove --name temporary_environment

Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: /home/pnguyen/miniconda3/envs/temporary_environment

  added / updated specs:
    - python=3.7

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/linux-64::certifi-2020.4.5.1-py37_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1g-h7b6447c_0
  pip                pkgs/main/linux-64::pip-20.0.2-py37_1
  python             pkgs/main/linux-64::python-3.7.7-hcf32534_0_cpython
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  setuptools         pkgs/main/linux-64::setuptools-46.1.3-py37_0
  sqlite             pkgs/main/linux-64::sqlite-3.31.1-h62c20be_1
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.34.2-py37_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3

Proceed ([y]/n)? 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate temporary_environment
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: /home/pnguyen/miniconda3/envs/temporary_environment

  added / updated specs:
    - cudatoolkit=10.1
    - cugraph

The following NEW packages will be INSTALLED:

  arrow-cpp          conda-forge/linux-64::arrow-cpp-0.15.0-py37h090bef1_2
  boost-cpp          conda-forge/linux-64::boost-cpp-1.70.0-h8e57a91_2
  brotli             conda-forge/linux-64::brotli-1.0.7-he1b5a44_1001
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_2
  c-ares             conda-forge/linux-64::c-ares-1.15.0-h516909a_1001
  cudatoolkit        nvidia/linux-64::cudatoolkit-10.1.243-h6bb024c_0
  cudf               rapidsai/linux-64::cudf-0.13.0-py37_0
  cudnn              nvidia/linux-64::cudnn-7.6.0-cuda10.1_0
  cugraph            rapidsai/linux-64::cugraph-0.13.0-py37_0
  cupy               conda-forge/linux-64::cupy-7.4.0-py37h0632833_1
  dlpack             conda-forge/linux-64::dlpack-0.2-he1b5a44_1
  double-conversion  conda-forge/linux-64::double-conversion-3.1.5-he1b5a44_2
  fastavro           conda-forge/linux-64::fastavro-0.23.3-py37h8f50634_0
  fastrlock          conda-forge/linux-64::fastrlock-0.4-py37h3340039_1001
  fsspec             conda-forge/noarch::fsspec-0.6.3-py_0
  gflags             conda-forge/linux-64::gflags-2.2.2-he1b5a44_1002
  glog               conda-forge/linux-64::glog-0.4.0-h49b9bf7_3
  grpc-cpp           conda-forge/linux-64::grpc-cpp-1.23.0-h18db393_0
  icu                conda-forge/linux-64::icu-64.2-he1b5a44_1
  libblas            conda-forge/linux-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-14_openblas
  libcudf            rapidsai/linux-64::libcudf-0.13.0-cuda10.1_0
  libcugraph         rapidsai/linux-64::libcugraph-0.13.0-cuda10.1_0
  libevent           conda-forge/linux-64::libevent-2.1.10-h72c5cf5_0
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_5
  liblapack          conda-forge/linux-64::liblapack-3.8.0-14_openblas
  libnvstrings       rapidsai/linux-64::libnvstrings-0.13.0-cuda10.1_0
  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h5ec1e0e_6
  libprotobuf        conda-forge/linux-64::libprotobuf-3.8.0-h8b12597_0
  librmm             rapidsai/linux-64::librmm-0.13.0-cuda10.1_0
  llvmlite           numba/linux-64::llvmlite-0.32.0-py37hf484d3e_0
  lz4-c              conda-forge/linux-64::lz4-c-1.8.3-he1b5a44_1001
  nccl               nvidia/linux-64::nccl-2.4.6.1-cuda10.1_0
  numba              numba/linux-64::numba-0.49.1rc1-np1.11py3.7h04863e7_gd9f05f89c_0
  numpy              conda-forge/linux-64::numpy-1.18.4-py37h8960a57_0
  nvstrings          rapidsai/linux-64::nvstrings-0.13.0-py37_0
  pandas             conda-forge/linux-64::pandas-0.25.3-py37hb3f55d8_0
  parquet-cpp        conda-forge/noarch::parquet-cpp-1.5.1-2
  pyarrow            conda-forge/linux-64::pyarrow-0.15.0-py37h8b68381_1
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/linux-64::python_abi-3.7-1_cp37m
  pytz               conda-forge/noarch::pytz-2020.1-pyh9f0ad1d_0
  re2                conda-forge/linux-64::re2-2020.05.01-he1b5a44_0
  rmm                rapidsai/linux-64::rmm-0.13.0-py37_0
  six                conda-forge/noarch::six-1.14.0-py_1
  snappy             conda-forge/linux-64::snappy-1.1.8-he1b5a44_1
  tbb                conda-forge/linux-64::tbb-2020.1-hc9558a2_0
  thrift-cpp         conda-forge/linux-64::thrift-cpp-0.12.0-hf3afdfd_1004
  uriparser          conda-forge/linux-64::uriparser-0.9.3-he1b5a44_1
  zstd               conda-forge/linux-64::zstd-1.4.3-h3b9ef0a_0

The following packages will be UPDATED:

  ca-certificates     pkgs/main::ca-certificates-2020.1.1-0 --> conda-forge::ca-certificates-2020.4.5.1-hecc5488_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi              pkgs/main::certifi-2020.4.5.1-py37_0 --> conda-forge::certifi-2020.4.5.1-py37hc8dfbb8_0
  openssl              pkgs/main::openssl-1.1.1g-h7b6447c_0 --> conda-forge::openssl-1.1.1g-h516909a_0

Proceed ([y]/n)? 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

/home/pnguyen/miniconda3/envs/temporary_environment/lib/python3.7/site-packages/cudf/utils/cudautils.py:7: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import requested from: 'numba.numpy_support', please update to use 'numba.np.numpy_support' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba import cuda, numpy_support
/home/pnguyen/miniconda3/envs/temporary_environment/lib/python3.7/site-packages/cudf/core/column/categorical.py:12: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import requested from: 'numba.numpy_support', please update to use 'numba.np.numpy_support' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from cudf._libxx.transform import bools_to_mask
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pnguyen/miniconda3/envs/temporary_environment/lib/python3.7/site-packages/cudf/__init__.py", line 7, in <module>
    from cudf import core, datasets
  File "/home/pnguyen/miniconda3/envs/temporary_environment/lib/python3.7/site-packages/cudf/core/__init__.py", line 5, in <module>
    from cudf.core.dataframe import DataFrame, from_pandas, merge
  File "/home/pnguyen/miniconda3/envs/temporary_environment/lib/python3.7/site-packages/cudf/core/dataframe.py", line 43, in <module>
    from cudf.utils import applyutils, ioutils, queryutils, utils
  File "/home/pnguyen/miniconda3/envs/temporary_environment/lib/python3.7/site-packages/cudf/utils/applyutils.py", line 6, in <module>
    from numba import cuda, six
ImportError: cannot import name 'six' from 'numba' (/home/pnguyen/miniconda3/envs/temporary_environment/lib/python3.7/site-packages/numba/__init__.py)
(temporary_environment) pnguyen@demouser-DGX-Station:/tmp$ (temporary_environment) pnguyen@demouser-DGX-Station:/tmp$ 
</details>

This form works fine:
<details>

(base) pnguyen@demouser-DGX-Station:/home/pnguyen$ cd /tmp/
(base) pnguyen@demouser-DGX-Station:/tmp$ yes | conda create -n temporary_environment python=3.7 && \
conda activate temporary_environment && \
yes | conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults cugraph cudatoolkit=10.1  && \
yes | conda install numba==0.48.0 && \
printf "\n\n\n\n" && \
python3 -c "import cudf, cugraph; print(f'cudf {cudf.__version__} \ncugraph {cugraph.__version__}')" && \
printf "\n\n\n\n" && \
conda deactivate && \
conda env remove --name temporary_environment
Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: /home/pnguyen/miniconda3/envs/temporary_environment

  added / updated specs:
    - python=3.7

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/linux-64::certifi-2020.4.5.1-py37_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1g-h7b6447c_0
  pip                pkgs/main/linux-64::pip-20.0.2-py37_1
  python             pkgs/main/linux-64::python-3.7.7-hcf32534_0_cpython
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  setuptools         pkgs/main/linux-64::setuptools-46.1.3-py37_0
  sqlite             pkgs/main/linux-64::sqlite-3.31.1-h62c20be_1
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.34.2-py37_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3

Proceed ([y]/n)? 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate temporary_environment
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: /home/pnguyen/miniconda3/envs/temporary_environment

  added / updated specs:
    - cudatoolkit=10.1
    - cugraph

The following NEW packages will be INSTALLED:

  arrow-cpp          conda-forge/linux-64::arrow-cpp-0.15.0-py37h090bef1_2
  boost-cpp          conda-forge/linux-64::boost-cpp-1.70.0-h8e57a91_2
  brotli             conda-forge/linux-64::brotli-1.0.7-he1b5a44_1001
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_2
  c-ares             conda-forge/linux-64::c-ares-1.15.0-h516909a_1001
  cudatoolkit        nvidia/linux-64::cudatoolkit-10.1.243-h6bb024c_0
  cudf               rapidsai/linux-64::cudf-0.13.0-py37_0
  cudnn              nvidia/linux-64::cudnn-7.6.0-cuda10.1_0
  cugraph            rapidsai/linux-64::cugraph-0.13.0-py37_0
  cupy               conda-forge/linux-64::cupy-7.4.0-py37h0632833_1
  dlpack             conda-forge/linux-64::dlpack-0.2-he1b5a44_1
  double-conversion  conda-forge/linux-64::double-conversion-3.1.5-he1b5a44_2
  fastavro           conda-forge/linux-64::fastavro-0.23.3-py37h8f50634_0
  fastrlock          conda-forge/linux-64::fastrlock-0.4-py37h3340039_1001
  fsspec             conda-forge/noarch::fsspec-0.6.3-py_0
  gflags             conda-forge/linux-64::gflags-2.2.2-he1b5a44_1002
  glog               conda-forge/linux-64::glog-0.4.0-h49b9bf7_3
  grpc-cpp           conda-forge/linux-64::grpc-cpp-1.23.0-h18db393_0
  icu                conda-forge/linux-64::icu-64.2-he1b5a44_1
  libblas            conda-forge/linux-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-14_openblas
  libcudf            rapidsai/linux-64::libcudf-0.13.0-cuda10.1_0
  libcugraph         rapidsai/linux-64::libcugraph-0.13.0-cuda10.1_0
  libevent           conda-forge/linux-64::libevent-2.1.10-h72c5cf5_0
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_5
  liblapack          conda-forge/linux-64::liblapack-3.8.0-14_openblas
  libnvstrings       rapidsai/linux-64::libnvstrings-0.13.0-cuda10.1_0
  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h5ec1e0e_6
  libprotobuf        conda-forge/linux-64::libprotobuf-3.8.0-h8b12597_0
  librmm             rapidsai/linux-64::librmm-0.13.0-cuda10.1_0
  llvmlite           numba/linux-64::llvmlite-0.32.0-py37hf484d3e_0
  lz4-c              conda-forge/linux-64::lz4-c-1.8.3-he1b5a44_1001
  nccl               nvidia/linux-64::nccl-2.4.6.1-cuda10.1_0
  numba              numba/linux-64::numba-0.49.1rc1-np1.11py3.7h04863e7_gd9f05f89c_0
  numpy              conda-forge/linux-64::numpy-1.18.4-py37h8960a57_0
  nvstrings          rapidsai/linux-64::nvstrings-0.13.0-py37_0
  pandas             conda-forge/linux-64::pandas-0.25.3-py37hb3f55d8_0
  parquet-cpp        conda-forge/noarch::parquet-cpp-1.5.1-2
  pyarrow            conda-forge/linux-64::pyarrow-0.15.0-py37h8b68381_1
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/linux-64::python_abi-3.7-1_cp37m
  pytz               conda-forge/noarch::pytz-2020.1-pyh9f0ad1d_0
  re2                conda-forge/linux-64::re2-2020.05.01-he1b5a44_0
  rmm                rapidsai/linux-64::rmm-0.13.0-py37_0
  six                conda-forge/noarch::six-1.14.0-py_1
  snappy             conda-forge/linux-64::snappy-1.1.8-he1b5a44_1
  tbb                conda-forge/linux-64::tbb-2020.1-hc9558a2_0
  thrift-cpp         conda-forge/linux-64::thrift-cpp-0.12.0-hf3afdfd_1004
  uriparser          conda-forge/linux-64::uriparser-0.9.3-he1b5a44_1
  zstd               conda-forge/linux-64::zstd-1.4.3-h3b9ef0a_0

The following packages will be UPDATED:

  ca-certificates     pkgs/main::ca-certificates-2020.1.1-0 --> conda-forge::ca-certificates-2020.4.5.1-hecc5488_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi              pkgs/main::certifi-2020.4.5.1-py37_0 --> conda-forge::certifi-2020.4.5.1-py37hc8dfbb8_0
  openssl              pkgs/main::openssl-1.1.1g-h7b6447c_0 --> conda-forge::openssl-1.1.1g-h516909a_0

Proceed ([y]/n)? 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: /home/pnguyen/miniconda3/envs/temporary_environment

  added / updated specs:
    - numba==0.48.0

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2020.4.5~ --> pkgs/main::ca-certificates-2020.1.1-0
  certifi            conda-forge::certifi-2020.4.5.1-py37h~ --> pkgs/main::certifi-2020.4.5.1-py37_0
  llvmlite            numba::llvmlite-0.32.0-py37hf484d3e_0 --> pkgs/main::llvmlite-0.31.0-py37hd408876_0
  numba              numba::numba-0.49.1rc1-np1.11py3.7h04~ --> pkgs/main::numba-0.48.0-py37h0573a6f_0
  openssl            conda-forge::openssl-1.1.1g-h516909a_0 --> pkgs/main::openssl-1.1.1g-h7b6447c_0

Proceed ([y]/n)? 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

cudf 0.13.0 
cugraph 0.13.0+0.gac36e8c.dirty

Remove all packages in environment /home/pnguyen/miniconda3/envs/temporary_environment:

(base) pnguyen@demouser-DGX-Station:/tmp$ 
</details>

Note that if I explicitly specify to use the older version of numba, I am able to import cugraph. 

**Expected behavior**

It would be nice if I could copy-&-paste the form shown on the README and be able to import cugraph afterward.

**Comment by Iroy30** [comment]
Hi @paul-tqh-nguyen , this error originates from cudf-0.13 version incompatibility with latest numba. cudf has since been updated to incorporate these numba changes. The conda install would work once 0.14 versions are released. Meanwhile, you could utilize the rapids nightly channels for conda installs which ensures you get all the latest changes, or, specify an older numba version.

**Comment by giovp** [comment]
As of today, this error still appears, with cudf 0.13 and numba 0.50.1 ...

**Comment by PierFio** [comment]
+1
